import type { LevelDef } from '../core/types.ts';

/** Levels 6-10 - a second patrol, then the camera grid. */
export const PACK_2: LevelDef[] = [
  {
    id: 6,
    name: 'PINCER',
    brief: 'Two halls, two guards, opposite phase. Ride the gap down.',
    map: [
      '###########',
      '#E.......$#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#....$....#',
      '#....S....#',
      '###########',
    ],
    guards: [
      {
        path: [
          [1, 6],
          [9, 6],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 10],
          [1, 10],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
    ],
  },
  {
    id: 7,
    name: 'EYE IN THE SKY',
    brief: 'A camera sweeps the gallery. It always sweeps the same way.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#$.......$#',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    cameras: [
      {
        x: 5,
        y: 6,
        from: 200,
        to: 340,
        sweepTicks: 90,
        holdTicks: 30,
        range: 5.4,
        halfAngle: 26,
      },
    ],
  },
  {
    id: 8,
    name: 'BLIND SPOT',
    brief: 'Pillars cast shadows. A lens cannot see through stone.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.#.#.#.#.#',
      '#$.......$#',
      '#.#.#.#.#.#',
      '#.........#',
      '#.#.#.#.#.#',
      '#....$....#',
      '#.#.#.#.#.#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    cameras: [
      {
        x: 5,
        y: 4,
        from: 150,
        to: 30,
        sweepTicks: 120,
        holdTicks: 30,
        range: 5.6,
        halfAngle: 28,
      },
      {
        x: 5,
        y: 12,
        from: 210,
        to: 330,
        sweepTicks: 120,
        holdTicks: 30,
        range: 5.6,
        halfAngle: 28,
        phase: 150,
      },
    ],
  },
  {
    id: 9,
    name: 'CROSSED LENSES',
    brief: 'One lens over the lobby, one over the loading bay.',
    map: [
      '###########',
      '#E.......$#',
      '#.........#',
      '#.........#',
      '#.#######.#',
      '#.#.....#.#',
      '#.#.....#.#',
      '#.#..$..#.#',
      '#.#.....#.#',
      '#.#.....#.#',
      '#.###.###.#',
      '#.........#',
      '#.........#',
      '#.#######.#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    cameras: [
      {
        x: 5,
        y: 2,
        from: 135,
        to: 45,
        sweepTicks: 105,
        holdTicks: 15,
        range: 5.6,
        halfAngle: 27,
      },
      {
        x: 5,
        y: 14,
        from: 225,
        to: 315,
        sweepTicks: 105,
        holdTicks: 15,
        range: 5.6,
        halfAngle: 27,
        phase: 120,
      },
    ],
  },
  {
    id: 10,
    name: 'WATCHED HALL',
    brief: 'A lens above, a guard below. They never sync up.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#$.......$#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#....S....#',
      '###########',
    ],
    cameras: [
      {
        x: 5,
        y: 6,
        from: 200,
        to: 340,
        sweepTicks: 105,
        holdTicks: 15,
        range: 5.6,
        halfAngle: 26,
      },
    ],
    guards: [
      {
        path: [
          [1, 10],
          [9, 10],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 14],
          [1, 14],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
    ],
  },
];
