import type { LevelDef } from '../core/types.ts';

/** Levels 16-20 - full patrol rosters. Every timing is a fixed loop. */
export const PACK_4: LevelDef[] = [
  {
    id: 16,
    name: 'THREE SHIFTS',
    brief: 'Three halls, three guards. One window lines them all up.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#$..S....$#',
      '###########',
    ],
    guards: [
      {
        path: [
          [1, 6],
          [9, 6],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 10],
          [1, 10],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 200,
      },
      {
        path: [
          [1, 14],
          [9, 14],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 400,
      },
    ],
  },
  {
    id: 17,
    name: 'CLOCKWORK',
    brief: 'Different speeds, same loop. Count the beats.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#$.......$#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    guards: [
      {
        path: [
          [1, 6],
          [9, 6],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 10],
          [1, 10],
        ],
        loop: 'pingpong',
        stepTicks: 45,
        pause: 90,
      },
      {
        path: [
          [1, 14],
          [9, 14],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
    ],
  },
  {
    id: 18,
    name: 'THE GALLERY',
    brief: 'Four on the floor. Two rings, two lines.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.#######.#',
      '#.#.....#.#',
      '#.#..$..#.#',
      '#.#.....#.#',
      '#.###.###.#',
      '#.........#',
      '#$.......$#',
      '#.........#',
      '#.###.###.#',
      '#.#.....#.#',
      '#.#..$..#.#',
      '#.#.....#.#',
      '#.#######.#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    guards: [
      {
        path: [
          [1, 2],
          [9, 2],
          [9, 8],
          [1, 8],
        ],
        loop: 'cycle',
        stepTicks: 30,
      },
      {
        path: [
          [9, 16],
          [1, 16],
          [1, 10],
          [9, 10],
        ],
        loop: 'cycle',
        stepTicks: 30,
        phase: 420,
      },
      {
        path: [
          [1, 9],
          [5, 9],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        range: 4.2,
      },
      {
        path: [
          [9, 9],
          [5, 9],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 180,
        range: 4.2,
      },
    ],
  },
  {
    id: 19,
    name: 'TIGHT LEASH',
    brief: 'Nine route changes, no more. Make every tap count.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#....$....#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#$..S....$#',
      '###########',
    ],
    maxWaypoints: 9,
    guards: [
      {
        path: [
          [1, 5],
          [9, 5],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 10],
          [1, 10],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
      {
        path: [
          [3, 13],
          [7, 13],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        range: 4.2,
      },
    ],
  },
  {
    id: 20,
    name: 'DOUBLE LOCK',
    brief: 'Four guards, two doors, one clean line through it all.',
    map: [
      '###########',
      '#....E....#',
      '#####B#####',
      '#.........#',
      '#....$....#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#....2....#',
      '#.........#',
      '#####A#####',
      '#.........#',
      '#....1....#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#$..S....$#',
      '###########',
    ],
    guards: [
      {
        path: [
          [1, 3],
          [9, 3],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 8],
          [1, 8],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
      {
        path: [
          [1, 12],
          [9, 12],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 150,
      },
      {
        path: [
          [3, 15],
          [7, 15],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        range: 4.2,
      },
    ],
  },
];
