import type { LevelDef } from '../core/types.ts';

/** Levels 11-15 - keycards and the doors they open. */
export const PACK_3: LevelDef[] = [
  {
    id: 11,
    name: 'KEYCARD',
    brief: 'Red card, red door. Nothing opens without it.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.........#',
      '#####A#####',
      '#.........#',
      '#$.......$#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#....1....#',
      '###.###.###',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    guards: [
      {
        path: [
          [1, 6],
          [9, 6],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
    ],
  },
  {
    id: 12,
    name: 'LOCKED WING',
    brief: 'The card sits in the back room. The door is three floors up.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#####A#####',
      '#.........#',
      '#$.......$#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.#.....#.#',
      '#.#..1..#.#',
      '#.#.....#.#',
      '#.###.###.#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    cameras: [
      {
        x: 5,
        y: 8,
        from: 200,
        to: 340,
        sweepTicks: 90,
        holdTicks: 30,
        range: 4.2,
        halfAngle: 28,
      },
      {
        x: 7,
        y: 4,
        from: 90,
        to: 170,
        sweepTicks: 75,
        holdTicks: 15,
        range: 5.2,
        halfAngle: 28,
        phase: 120,
      },
    ],
  },
  {
    id: 13,
    name: 'TWO CARDS',
    brief: 'Red opens the stairs. Green opens the roof.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#####B#####',
      '#.........#',
      '#..2...$..#',
      '#.........#',
      '#####A#####',
      '#.........#',
      '#.........#',
      '#..1...$..#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    guards: [
      {
        path: [
          [1, 9],
          [9, 9],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 4],
          [1, 4],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
    ],
  },
  {
    id: 14,
    name: 'ESCORT',
    brief: 'He rings the whole floor. Two cases sit on his path.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.#######.#',
      '#.#.....#.#',
      '#.#..$..#.#',
      '#.#.....#.#',
      '#.###A###.#',
      '#.........#',
      '#....1....#',
      '#$.......$#',
      '#.........#',
      '#.#######.#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    guards: [
      {
        path: [
          [1, 2],
          [9, 2],
          [9, 11],
          [1, 11],
        ],
        loop: 'cycle',
        stepTicks: 30,
      },
    ],
  },
  {
    id: 15,
    name: 'CHAIN',
    brief: 'Each card opens the door that hides the next one.',
    map: [
      '###########',
      '#....E....#',
      '#####C#####',
      '#.........#',
      '#....3....#',
      '#.#######.#',
      '#.#..$..#.#',
      '#.#.....#.#',
      '#.###B###.#',
      '#.........#',
      '#....2....#',
      '#.........#',
      '#####A#####',
      '#.........#',
      '#..1...$..#',
      '#....S....#',
      '###########',
    ],
    cameras: [
      {
        x: 3,
        y: 13,
        from: 160,
        to: 20,
        sweepTicks: 90,
        holdTicks: 30,
        range: 5.2,
        halfAngle: 28,
      },
    ],
    guards: [
      {
        path: [
          [1, 9],
          [9, 9],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
    ],
  },
];
