import type { LevelDef } from '../core/types.ts';

/** Levels 26-30 - everything at once, and the finale. */
export const PACK_6: LevelDef[] = [
  {
    id: 26,
    name: 'PENTHOUSE',
    brief: 'Card, lens, patrol, beam. One clean line exists.',
    map: [
      '###########',
      '#....E....#',
      '#####A#####',
      '#.........#',
      '#....$....#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#$..1....$#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    lasers: [{ a: [1, 12], b: [9, 12], on: 60, off: 120 }],
    cameras: [
      {
        x: 5,
        y: 5,
        from: 200,
        to: 340,
        sweepTicks: 90,
        holdTicks: 30,
        range: 5.4,
        halfAngle: 26,
      },
    ],
    guards: [
      {
        path: [
          [1, 8],
          [9, 8],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
    ],
  },
  {
    id: 27,
    name: 'BLACK SITE',
    brief: 'Two wings, two cards, one shared corridor.',
    map: [
      '###########',
      '#....E....#',
      '#####B#####',
      '#.........#',
      '#..$...$..#',
      '#.........#',
      '###.###.###',
      '#....2....#',
      '#..~...~..#',
      '#####A#####',
      '#.........#',
      '#..1......#',
      '#..~...~..#',
      '###.###.###',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    lasers: [
      { a: [1, 5], b: [9, 5], on: 60, off: 120 },
      { a: [1, 10], b: [9, 10], on: 60, off: 120, phase: 90 },
    ],
    guards: [
      {
        path: [
          [1, 8],
          [9, 8],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 12],
          [1, 12],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
    ],
  },
  {
    id: 28,
    name: 'THE VAULT',
    brief: 'The prize is ringed by a patrol and lit by two lenses.',
    map: [
      '###########',
      '#....E....#',
      '#.........#',
      '#.#######.#',
      '#.#.....#.#',
      '#.#.###.#.#',
      '#.#.#$#.#.#',
      '#.#.#.#.#.#',
      '#.#..1..#.#',
      '#.###.###.#',
      '#.........#',
      '#$.......$#',
      '#.........#',
      '#.#######.#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    cameras: [
      {
        x: 5,
        y: 12,
        from: 180,
        to: 0,
        sweepTicks: 90,
        holdTicks: 30,
        range: 5.4,
        halfAngle: 24,
      },
      {
        x: 5,
        y: 2,
        from: 150,
        to: 30,
        sweepTicks: 75,
        holdTicks: 15,
        range: 5.4,
        halfAngle: 26,
        phase: 90,
      },
    ],
    guards: [
      {
        path: [
          [1, 2],
          [9, 2],
          [9, 12],
          [1, 12],
        ],
        loop: 'cycle',
        stepTicks: 30,
      },
    ],
  },
  {
    id: 29,
    name: 'LOCKDOWN',
    brief: 'Three guards, one beam, one card. Nine taps, no more.',
    map: [
      '###########',
      '#....E....#',
      '#####A#####',
      '#.........#',
      '#$.......$#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#....1....#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#.........#',
      '#....S....#',
      '###########',
    ],
    maxWaypoints: 9,
    lasers: [{ a: [1, 11], b: [9, 11], on: 60, off: 120 }],
    guards: [
      {
        path: [
          [1, 4],
          [9, 4],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 8],
          [1, 8],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
      {
        path: [
          [3, 12],
          [7, 12],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        range: 4.2,
      },
    ],
  },
  {
    id: 30,
    name: 'TINY HEIST',
    brief: 'Everything they have. Take it all and walk out.',
    map: [
      '###########',
      '#....E....#',
      '#####B#####',
      '#.........#',
      '#$.......$#',
      '#.........#',
      '###.###.###',
      '#.........#',
      '#....2....#',
      '#..~...~..#',
      '#####A#####',
      '#.........#',
      '#..1...$..#',
      '#.........#',
      '###.###.###',
      '#..~...~..#',
      '#....S....#',
      '###########',
    ],
    maxWaypoints: 13,
    lasers: [
      { a: [1, 3], b: [9, 3], on: 60, off: 120 },
      { a: [1, 13], b: [9, 13], on: 60, off: 120, phase: 90 },
    ],
    cameras: [
      {
        x: 5,
        y: 5,
        from: 200,
        to: 340,
        sweepTicks: 90,
        holdTicks: 30,
        range: 5.4,
        halfAngle: 26,
      },
    ],
    guards: [
      {
        path: [
          [1, 8],
          [9, 8],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
      },
      {
        path: [
          [9, 11],
          [1, 11],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        phase: 300,
      },
      {
        path: [
          [3, 15],
          [7, 15],
        ],
        loop: 'pingpong',
        stepTicks: 30,
        pause: 60,
        range: 4.2,
      },
    ],
  },
];
