// AUTO-GENERATED by `npm run validate`. Do not edit by hand.
//
// `optimal` is the fastest fully-undetected run the solver could find, `taps`
// is how many path commands that run needs, and `par` is the 2-star target.
export interface LevelTuning {
  par: number;
  optimal: number;
  taps: number;
}

export const TUNING: Record<number, LevelTuning> = {
  1: { par: 8, optimal: 5.5, taps: 2 },
  2: { par: 12, optimal: 8.5, taps: 3 },
  3: { par: 20, optimal: 14, taps: 2 },
  4: { par: 10, optimal: 6.5, taps: 3 },
  5: { par: 12, optimal: 8.25, taps: 3 },
  6: { par: 12, optimal: 8, taps: 3 },
  7: { par: 12, optimal: 8.5, taps: 4 },
  8: { par: 12, optimal: 8.5, taps: 4 },
  9: { par: 15, optimal: 10.5, taps: 4 },
  10: { par: 14, optimal: 9.75, taps: 5 },
  11: { par: 13, optimal: 8.75, taps: 5 },
  12: { par: 16, optimal: 10.75, taps: 6 },
  13: { par: 14, optimal: 9.75, taps: 8 },
  14: { par: 14, optimal: 9.75, taps: 4 },
  15: { par: 18, optimal: 12.25, taps: 9 },
  16: { par: 13, optimal: 9, taps: 4 },
  17: { par: 11, optimal: 7.75, taps: 3 },
  18: { par: 35, optimal: 24.5, taps: 11 },
  19: { par: 16, optimal: 10.75, taps: 6 },
  20: { par: 23, optimal: 16, taps: 10 },
  21: { par: 12, optimal: 8.5, taps: 3 },
  22: { par: 11, optimal: 7.25, taps: 4 },
  23: { par: 13, optimal: 8.75, taps: 5 },
  24: { par: 12, optimal: 8.5, taps: 5 },
  25: { par: 25, optimal: 17.5, taps: 12 },
  26: { par: 15, optimal: 10.5, taps: 7 },
  27: { par: 11, optimal: 7.5, taps: 4 },
  28: { par: 18, optimal: 12.25, taps: 5 },
  29: { par: 19, optimal: 13, taps: 8 },
  30: { par: 29, optimal: 20.25, taps: 11 },
};
